<?xml version="1.0"?>
<robot name="pan_tilt" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="base_link_length" value="0.03" />
    <xacro:property name="base_link_radius" value="0.4" />

    <xacro:property name="pan_link_length" value="1.5" />
    <xacro:property name="pan_link_radius" value="0.04" />

    <xacro:property name="tilt_link_length" value="0.2" />
    <xacro:property name="tilt_link_radius" value="0.04" />


  <link name="world"/>

    <joint name="world_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <static>0</static>
    </joint> 

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
            </geometry>
          <origin xyz="0.0 0.0 0.30" rpy="0.0 0.0 0.0"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${base_link_radius}" length="${base_link_length}"/>
            </geometry>
           <origin xyz="0.0 0.0 0.30" rpy="0.0 0.0 0.0"/>
        </collision>

        <inertial>
            <mass value="10.0"/>
            <inertia ixx="0.40075" ixy="0.0" ixz="0.0" iyy="0.40075" iyz="0.0" izz="0.8"/>            
        </inertial>
    </link>

    <joint name="pan_joint" type="revolute">
        <parent link="base_link"/>
        <child link="pan_link"/>
        <origin xyz="0.0 0.0 0.315"/>
        <axis xyz="0.0 0.0 1.0"/>
       <limit lower="-1000000" upper="1000000" effort="300" velocity="0.1"/>
        <dynamics damping="50" friction="1"/>
    </joint>


    <link name="pan_link">
        <visual>
            <geometry>
                <cylinder radius="${pan_link_radius}" length="${pan_link_length}"/>
            </geometry>
        <origin xyz="0.0 0.0 0.75" rpy="0.0 0.0 0.0"/>
        <material name="red">
            <color rgba="0 0 1 1"/>
        </material>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${pan_link_radius+0.02}" length="${pan_link_length}"/>
            </geometry>    
        <origin xyz="0.0 0.0 0.75" rpy="0.0 0.0 0.0"/>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <inertia ixx="3.75" ixy="0.0" ixz="0.0" iyy="3.75" iyz="0.0" izz="0.04"/>
        </inertial>
    </link>


    <joint name="tilt_joint" type="revolute">
        <parent link="pan_link"/>
        <child link="tilt_link"/>
        <origin xyz="0.0 0.09 1.5"/>
        <axis xyz="0.0 1.0 0.0"/>
       <limit lower="-1000000" upper="1000000" effort="300.0" velocity="0.5"/>
        <dynamics damping="50" friction="1"/>
    </joint>


    <link name="tilt_link">
        <visual>
            <geometry>
                <cylinder radius="${tilt_link_radius}" length="${tilt_link_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.1" rpy="0.0 0 0.0"/>
            <material name="green">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${tilt_link_radius+0.2}" length="${tilt_link_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.1" rpy="0.0 0 0.0"/>
        </collision>

        <inertial>
            <mass value="5.0"/>
            <inertia ixx="0.266" ixy="0.0" ixz="0.0" iyy="0.266" iyz="0.0" izz="0.4"/>    
        </inertial>
    </link>

    <joint name="camera_joint" type="fixed">
      <origin xyz="0.0 0.0 0.22" rpy="0 -1.5707 0.0"/>
      <parent link="tilt_link"/>
      <child link="camera_bottom_screw_frame" />
    </joint>
    <link name="camera_bottom_screw_frame"/>

    <joint name="camera_link_joint" type="fixed">
      <origin xyz="0 0.0175 0.0125" rpy="0 0 0"/>
      <parent link="camera_bottom_screw_frame"/>
      <child link="camera_link" />
    </joint>

    <link name="camera_link">
    
      <visual>
      <origin xyz="0.0149 0.0175 0" rpy="1.5707 0 1.5707"/>
        <geometry>
          <!-- <box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
          <mesh filename="model://intel_realsense_d435/meshes/d435.dae" />
          <!--<mesh filename="package://realsense2_description/meshes/d435/d435.dae" />-->
        </geometry>
        <material name="camera_aluminum"/>
      </visual>
      <collision>
        <origin xyz="0 -0.0175 0" rpy="0 0 0"/>
        <geometry>
        <box size="0.02505 0.090 0.025"/>
        </geometry>
      </collision>
      <inertial>
        
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
  </link>
   
    
    <joint name="camera_depth_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="camera_link"/>
      <child link="camera_depth_frame" />
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
      <parent link="camera_depth_frame" />
      <child link="camera_depth_optical_frame" />
    </joint>
    <link name="camera_depth_optical_frame"/>

      
    
    <joint name="$camera_left_ir_joint" type="fixed">
      <origin xyz="0 0.0 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_left_ir_frame" />
    </joint>
    <link name="camera_left_ir_frame"/>

    <joint name="camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
      <parent link="camera_left_ir_frame" />
      <child link="camera_left_ir_optical_frame" />
    </joint>
    <link name="camera_left_ir_optical_frame"/>
    
    

    
    <joint name="camera_right_ir_joint" type="fixed">
      <origin xyz="0 -0.050 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_right_ir_frame" />
    </joint>
    <link name="camera_right_ir_frame"/>

    <joint name="camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
      <parent link="camera_right_ir_frame" />
      <child link="camera_right_ir_optical_frame" />
    </joint>
    <link name="camera_right_ir_optical_frame"/>
    

    
    <joint name="camera_color_joint" type="fixed">
      <origin xyz="0 0.015 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_color_frame" />
    </joint>
    <link name="camera_color_frame"/>

    <joint name="camera_color_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
      <parent link="camera_color_frame" />
      <child link="camera_color_optical_frame" />
    </joint>
    <link name="camera_color_optical_frame"/>

    <gazebo reference="camera_link">
     <self_collide>0</self_collide>
      <enable_wind>0</enable_wind>
      <kinematic>0</kinematic>
      <gravity>0</gravity>
      <!--<mu>1</mu>-->
      <mu2>1</mu2>
      <fdir1>0 0 0</fdir1>
      <!--<slip1>0</slip1>
      <slip2>0</slip2>-->
      <kp>1e+13</kp>
      <kd>1</kd>
      <sensor name="cameracolor" type="camera">
        <camera name="camera">
          <horizontal_fov>1.211258501</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>RGB_INT8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>30</update_rate>
        <visualize>1</visualize>
      </sensor>
      <sensor name="cameraired1" type="camera">
        <camera name="camera">
          <horizontal_fov>1.487020523</horizontal_fov>
          <image>
            <width>1280</width>
            <height>720</height>
            <format>L_INT8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.05</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>90</update_rate>
        <visualize>1</visualize>
      </sensor>
      <sensor name="cameraired2" type="camera">
        <camera name="camera">
          <horizontal_fov>1.487020523</horizontal_fov>
          <image>
            <width>1280</width>
            <height>720</height>
            <format>L_INT8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.05</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>90</update_rate>
        <visualize>1</visualize>
      </sensor>
      <sensor name="cameradepth" type="depth">
        <camera name="camera">
          <horizontal_fov>1.487020523</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
          </image>
          <clip>
            <near>0.1</near>
            <far>100</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.100</stddev>
          </noise>
        </camera>
        <always_on>1</always_on>
        <update_rate>90</update_rate>
        <visualize>1</visualize>
      </sensor>
    </gazebo>
    <gazebo>
    <plugin name="gazebo_api" filename="libgazebo_ros_api_plugin.so"/>
    <plugin name="my_pantilt2" filename="libmypantilt2_plugin.so"/>
    <plugin name="my_pantilt1" filename="libmypantilt1_plugin.so"/>
    <plugin name="camera" filename="librealsense_gazebo_plugin.so">
        <prefix>camera</prefix>
        <depthUpdateRate>30.0</depthUpdateRate>
        <colorUpdateRate>30.0</colorUpdateRate>
        <infraredUpdateRate>30.0</infraredUpdateRate>
        <depthTopicName>depth/image_raw</depthTopicName>
        <depthCameraInfoTopicName>depth/camera_info</depthCameraInfoTopicName>
        <colorTopicName>color/image_raw</colorTopicName>
        <colorCameraInfoTopicName>color/camera_info</colorCameraInfoTopicName>
        <infrared1TopicName>infra1/image_raw</infrared1TopicName>
        <infrared1CameraInfoTopicName>infra1/camera_info</infrared1CameraInfoTopicName>
        <infrared2TopicName>infra2/image_raw</infrared2TopicName>
        <infrared2CameraInfoTopicName>infra2/camera_info</infrared2CameraInfoTopicName>
        <colorOpticalframeName>camera_color_optical_frame</colorOpticalframeName>
        <depthOpticalframeName>camera_depth_optical_frame</depthOpticalframeName>
        <infrared1OpticalframeName>camera_left_ir_optical_frame</infrared1OpticalframeName>
        <infrared2OpticalframeName>camera_right_ir_optical_frame</infrared2OpticalframeName>
        <rangeMinDepth>0.2</rangeMinDepth>
        <rangeMaxDepth>10.0</rangeMaxDepth>
        <pointCloud>true</pointCloud>
        <pointCloudTopicName>depth/color/points</pointCloudTopicName>
        <pointCloudCutoff>0.25</pointCloudCutoff>
        <pointCloudCutoffMax>9.0</pointCloudCutoffMax>
      </plugin>
</gazebo>
</robot>
